// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfbssqbrgogwtvkdvpmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmYnNzcWJyZ29nd3R2a2R2cG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODY5NTksImV4cCI6MjA2ODY2Mjk1OX0.gQfjK3Ml6qFVFPC5Pwd8iCjOJHYI4zZI_hxnADHV7AQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});